//@author ypijs.org#license 2014
function g(b){var a={H:[],qa:[]};a.name=b.Name;a.Va=b.Alias;a.Ab=b.TextAbout;a.speed=b.Speed;a.Ba=b.IdleInterval;a.message=void 0;a.oa=1;a.Nb=void 0;a.I="#"+b.BubbleId;a.ma=b.onbubble;a.Ja=b.onplay;a.Na=b.onstop;a.Ia=b.onmute;a.Vb=b.onaction;a.La=b.onseek;a.Ma=b.onsetter;a.X=b.onfinish;a.ea=b.behavior;a.M=!1;a.u=0;a.k=0;a.p=0;a.xb=function(b){a.qa=b.split("\\n");a.p=0;a.k=0};a.wb=function(b){a.na=b};a.getParams=function(){return a.na};a.getName=function(){return a.name};a.getAlias=function(){return a.Va};
a.Aa=function(){return a.k<a.qa.length};a.qb=function(){if(a.Aa())return a.k+=1,a.qa[a.k-1]};a.registerCustomAction=function(b,f){a.H[b]=f};a.update=function(b,f){a.Db();return void 0==a.H[b]||void 0==a.H[b].Sa||a.H[b].m!=f.m?!1:a.H[b].Sa(void 0,f)};a.Db=function(){a.oa=1;void 0!=a.U&&clearTimeout(a.U)};a.C=function(b,f){void 0!=f&&(a.first=f.sa,a.u=0);a.p=0;a.message=b;void 0!=a.U&&clearTimeout(a.U);a.M&&(clearTimeout(a.timeout),a.M=!1);a.xb(b);a.Qa()};a.Qa=function(){retVal=!0;void 0!=a.Ja&&h.L&&
(retVal=!a.Ja(a));retVal&&a.show()};a.show=function(){a.Ea?a.xa=!0:a.Ya(a.qb())};a.skip=function(){clearTimeout(a.timeout);a.mute()};a.repeat=function(){a.C(a.message);a.oa++};a.about=function(b){temp=a.message;a.C(b);a.message=temp};a.getTextAbout=function(){return a.Ab};a.getTextId=function(){return a.p};a.Ya=function(b){void 0!=a.ma?(px={},px.Text=b,px.Element=$(a.I),a.ma(px,a)):$(a.I).text(b);retVal=a.M=!0;void 0!=a.La&&h.L&&(retVal=!a.La(a));retVal&&(a.timeout=setTimeout(function(){a.M&&a.mute()},
b.length*a.speed));$(a.I).fadeIn(30,function(){a.first&&(a.u+=h.yb(a.na),a.first=!1);a.u+=h.Bb(a.na,a.p)})};a.isSpeaking=function(){return a.M};a.mute=function(){void 0!=a.Ia&&a.Ia(a);a.Ea=!0;$(a.I).fadeOut("slow",a.pb)};a.getReactCnt=function(){return a.u};a.pb=function(){a.Ea=!1;a.xa?(a.xa=!1,a.show()):a.Aa()?(a.p+=1,a.Qa()):h.Fa()||a.Cb()};a.Cb=function(){void 0!=a.Na&&a.Na(a);a.p=0;void 0!=a.Ba&&(a.U=setTimeout(function(){void 0!=h.R&&void 0!=h.R.r?h.P(h.R.r):a.repeat()},a.Ba*a.oa))};return a}
function k(){return hR={update:function(b){$("#history").empty();$.each(b.la,function(){historyItem=this;$("<strong>"+historyItem.ra+"</strong><p>"+historyItem.b+"</p>").appendTo("#history")});$hide=$("<a>hide</a>");$hide.click(function(){b.hide();$("#history_panel").fadeOut("fast");$("#history").empty()}).appendTo("#history")},tb:function(b){$("#history_panel").fadeIn("fast");hR.update(b)}}}
function l(){mH={la:{},Ra:{},Xb:{},Oa:void 0,ka:!1};mH.e=k();mH.k=0;mH.Pa=function(b){mH.Ra[b.t]=!0;mH.la[mH.k]=b;mH.k++;mH.update()};mH.vb=function(b){mH.Oa=b};mH.Ob=function(){return mH.Oa};mH.nb=function(b){return!0==mH.Ra[b]};mH.show=function(){mH.ka=!0;mH.e.tb(mH)};mH.update=function(){mH.ka&&mH.e.update(mH)};mH.hide=function(){mH.ka=!1};return mH}
function m(){aU={j:[],q:[]};var b=l();aU.register=function(a,b){aU.j[a]=b;void 0!=b.ea&&b.ea(b)};aU.reset=function(){aU.q=[]};aU.pa=function(a){if(isNaN(a.G))return!1;void 0==aU.q[a.h]&&(aU.q[a.h]=0);if("+="==a.ba)aU.q[a.h]+=Number(a.G);else if("="==a.ba)aU.q[a.h]=Number(a.G);else return!1;void 0!=aU.N&&aU.N(a);return!0};aU.T=function(a){return aU.q[a]};aU.kb=function(){for(var a in aU.j)void 0!=aU.j[a].Ma&&aU.j[a].Ma()};aU.ya=function(a){return aU.j[a]};aU.A=function(){return b};aU.C=function(a,
c){void 0!=c.s&&void 0!=aU.j[c.s]&&($v=$(aU.j[c.s].I),void 0!=$v&&"hide"!=c.Ta&&(b.Pa({ra:c.s,b:a}),aU.j[c.s].C(a,c)))};return aU}
function n(b,a){pR={};pR.d=a;pR.ja=void 0;pR.K=b.initState;pR.V=b.isAutostart;pR.xml=void 0;pR.load=function(a){pR.ja=!1;$.ajax({type:"GET",url:a,dataType:"xml",success:function(a){pR.xml=$(a);pR.ja=!0;void 0!=pR.V&&void 0!=pR.K&&pR.V&&pR.d.P(pR.K)},error:function(){void 0!=pR.d.Ga&&pR.d.Ga(a)}})};pR.za=function(a){var b={};$.each(pR.d.Wa,function(e,d){b[d.charAt(0).toUpperCase()+d.substring(1)]=a.getAttribute(d)});b.b=b.Text;b.i=b.Target;b.aa=b.Invoke;b.Hb=b.Overtime;b.Jb=b.Timeout;b.D=b.Condition;
b.m=b.Scope;b.ca=b.Sound;b.F=b.Id;void 0!=pR.d.ta&&$.each(pR.d.ta,function(e,d){b[d.charAt(0).toUpperCase()+d.substring(1)]=a.getAttribute(d)});return void 0==b.b?void 0:b};pR.fb=function(){var a=element,b={};b.l=a.getAttribute("prop");$.each(pR.d.Xa,function(e,d){b[d.charAt(0).toUpperCase()+d.substring(1)]=a.getAttribute(d)});b.r=b.Goto;b.b=b.Text;b.D=b.Condition;b.l=b.Prop;b.Q=b.Setter;b.ca=b.Sound;b.aa=b.Invoke;b.m=b.Scope;void 0!=pR.d.ua&&$.each(pR.d.ua,function(e,d){b[d.charAt(0).toUpperCase()+
d.substring(1)]=a.getAttribute(d)});return void 0==b.b&&void 0==GotoId?void 0:b};pR.ob=function(a,b,e){diff=100-b;0<diff&&(p=Math.floor(diff/e),$.each(a,function(){void 0==this.l&&(this.l=p)}))};pR.rb=function(b){tokens=b.split(";");for(i=0;i<tokens.length;i++)0==tokens[i].indexOf("_")&&0<tokens[i].indexOf("=")&&(variables=tokens[i].split("="),isNaN(variables[1])?alert(tokens[i]+": invalid number format"):variables[0].indexOf("+")==variables[0].length-1?a.g.pa({h:variables[0].substring(0,variables[0].length-
1),ba:"+=",G:variables[1]}):a.g.pa({h:variables[0],ba:"=",G:variables[1]}));a.g.kb()};pR.cb=function(a){var b=Math.floor(100*Math.random()+1),e=void 0,d=0;$.each(a,function(){if(pR.mb(this,b,d))return e=this,!1;d+=Number(this.l);return!0});return e};pR.mb=function(a,b,e){return b>e&&b<=e+Number(a.l)};pR.ha=function(){return pR.xml};pR.eb=function(a,b){if(void 0==b)return a;x=a.lastIndexOf(".");if(0>=x)return a;prefix=a.substring(0,x);suffix=a.substring(x,a.length);return prefix+"_"+b+suffix};return pR}
function q(b){iN={data:"",index:0,lastIndex:0,la:"",S:0,N:void 0};void 0!=b&&void 0!=b.onvariable&&(iN.N=b.onvariable);iN.log=function(){};iN.evaluate=function(a){iN.data=decodeURI(a.replace(/\^/g,"&"));iN.index=0;iN.S=0;return r=iN.w()};iN.w=function(){expected=iN.next();if("("==expected){iN.S++;tmp=iN.w();expected=iN.next();if(")"==expected)return iN.S--,expected=iN.next(),"|"==expected?tmp|=iN.w():")"==expected?iN.O():"&"==expected?tmp&=iN.w():iN.B()||iN.c(expected,"& or |"),tmp;iN.c(expected,
")")}else{if("_"==expected)return tmp=iN.$a(),expected=iN.next(),"|"==expected?tmp|=iN.w():"&"==expected?tmp&=iN.w():")"==expected?(0>=iN.S&&iN.c(expected,"unexpected )"),iN.O()):iN.B()||iN.c(expected,"& or |"),tmp;iN.c(expected,"_ or (")}};iN.$a=function(){variable=iN.T();val=0;void 0!=iN.N&&(val=iN.N("_"+variable),void 0==val&&(val=0));expected=iN.next();"="==expected?tmp=val==iN.ga():">"==expected?tmp=val>iN.ga():"<"==expected?tmp=val<iN.ga():iN.c("bad operator","expected ><=");return tmp};iN.Qb=
function(a){return"x"==a?1:0};iN.T=function(){for(str="";;){expected=iN.next();if("="==expected||">"==expected||"<"==expected)return iN.O(),""==str?iN.c("empty name of property"):iN.log("got variable "+str),str;if("\n"==expected||iN.B()){iN.c(expected);break}else str+=expected}};iN.ga=function(){str="";expected=iN.next();for("-"==expected?str+=expected:iN.O();;)if(expected=iN.next(),"1"==expected||"2"==expected||"3"==expected||"4"==expected||"5"==expected||"6"==expected||"7"==expected||"8"==expected||
"9"==expected||"0"==expected)str+=expected;else{if("&"==expected||"|"==expected||"\n"==expected||")"==expected||","==expected||"+"==expected||iN.B())return iN.O(),""==str&&iN.c("empty constant"),str;iN.c(expected,"");break}};iN.c=function(a,b){throw'error: "'+a+'",'+b;};iN.B=function(){return iN.index+1>iN.data.length};iN.O=function(){iN.index=iN.lastIndex};iN.zb=function(){for(;!(iN.index++,iN.B()||"\r"!=iN.data.charAt(iN.index-1)&&" "!=iN.data.charAt(iN.index-1)););};iN.next=function(){return iN.B()?
null:(iN.lastIndex=iN.index,iN.zb(),iN.data.charAt(iN.index-1))};return iN}
function t(){return rd={wa:function(b,a){if(b.lb||a.W&&void 0!=b.D&&1!=a.evaluate(b.D))return!1;cssClass="";a.A().nb(b.t)&&(cssClass="class=visited");if(void 0!=b)return s=void 0,void 0!=a.Ka&&(s=a.Ka(b)),void 0==s&&(s=$("<li "+cssClass+"></li>").html('<a href="#'+b.i+'_area">'+b.b+"</a>")),s.click({b:b.b,r:b.r,t:b.t,$:b.$,Q:b.Q,Ua:b},function(b){a.A().vb(b.data.$);a.A().Pa({ra:"you",b:b.data.b,t:b.data.t});void 0!=b.data.Q&&a.a.rb(b.data.Q);a.P(b.data.r);void 0!=a.Ha&&a.Ha(b.data.Ua)}),s.appendTo("#answers"),
b.lb=!0},ub:function(b){return b},Ca:function(){$('<ul id="answers"></ul>').appendTo("#dialog")}}}
var h=function(){var b={init:function(a){b.a=void 0;b.e=void 0;b.g=m();b.v=void 0;b.J=a.chapterUrl;b.Da=a.onload;b.Ha=a.onanswer;b.Ka=a.onrender;b.Ga=a.on404;b.Y=a.onsound;b.X=a.onfinish;b.ta=a.attrCase;b.ua=a.attrReact;b.Wa="id text target sound overtime timeout invoke scope condition setter".split(" ");b.Xa="text goto condition invoke sound setter scope prop".split(" ");b.language=a.language;b.a=n(a,b);b.e=t();b.L=!1;b.L=a.isSoundEnabled;b.W=!0;b.ia=void 0;!1==a.isExprEnabled&&(b.W=!1);b.va=a.disableBubbleRender;
b.da=1;b.Z=0},invokeInit:function(){if(void 0==b.Da||void 0==b.a)return!1;b.e.Ca();b.Da();b.ib();void 0!=b.J&&(b.W&&(b.ia=q({onvariable:b.g.T})),b.a.load(b.a.eb(b.J,b.language)))},reset:function(){b.g.reset();b.P(b.a.K);temp=avatar.message},o:function(){return b.g},Pb:function(){return b.e()},createAvatar:function(a){void 0==a.BubbleId&&(a.BubbleId="npc_bubble_"+b.da);void 0==a.Name&&(a.Name="avatar_"+b.da);a=g(a);if(void 0!=a&&void 0!=b.o())return b.o().register(a.name,a),b.da++,a},A:function(){return b.o().A()},
gotoChapter:function(a){void 0!=a.nodeId&&(b.g.reset(),void 0!=a.chapterUrl&&a.chapterUrl!=b.J?(b.a.K=a.nodeId,b.J=a.chapterUrl,b.a.V=!0,b.a.load(b.J)):b.P(a.nodeId))},P:function(a){if(void 0==b.a||!0!=b.a.ja)return!1;$("#answers").empty();var c;b.a.ha().find("case[id="+a+"]").each(function(){c=this});a=b.a.za(c);if(void 0==a)return!1;b.bb(a);b.ab(a);b.Z=0;b.fa=a;void 0!=a.n?b.Fa():b.show(a)},Fa:function(){if(void 0==b.fa.n||b.Z>=b.fa.n.length)return!1;params=b.fa.n[b.Z];b.Z++;b.show(params);return!0},
bb:function(a){tCnt=0;b.a.ha().find("txt[rel="+a.F+"]").each(function(){element=this;params=b.a.za(element);void 0!=params.b&&b.W&&void 0!=params.D&&1!=b.evaluate(params.D)||(void 0==a.n&&(a.n=[],void 0!=a.b&&0<a.b.length?(a.n[tCnt]=a,tCnt++):(params.i=a.i,params.F=a.F)),a.n[tCnt]=params,tCnt++)})},yb:function(){key="unsorted";cnt=0;if(void 0==b.f||void 0==b.f[key])return cnt;$.each(b.f[key],function(a,c){b.e.wa(c,b)&&cnt++});return cnt},Bb:function(a,c){cnt=0;if(void 0==a.m)return cnt;key="t_"+a.m+
"_"+c;if(void 0==b.f||void 0==b.f[key])return cnt;$.each(b.f[key],function(a,c){b.e.wa(c,b)&&cnt++});return cnt},ab:function(a){var c=0,f=0,e=0;reactions=[];b.R=void 0;b.f={};nodeId=a.F;b.a.ha().find("react[rel="+nodeId+"]").each(function(){element=this;params=b.a.fb();params.t=nodeId+""+params.r;params.$=nodeId;params.i=a.i;void 0!=params.l?e+=Number(params.l):f+=1;reactions[c]=params;b.sb(params);c++});b.R=b.gb(reactions,e,f)},sb:function(a){key=b.hb(a);void 0==b.f[key]&&(b.f[key]=[]);b.f[key].push(a)},
hb:function(a){return void 0==a.m?"unsorted":"t_"+a.m},show:function(a){b.jb(a)},gb:function(a,c,f){if(0<c)return b.a.ob(a,c,f),b.a.cb(a)},update:function(a,c){0==c&&void 0!=b.X&&b.X(a)},invokeActions:function(a){avatar=h.o().ya(b.v);void 0!=avatar&&void 0!=a.aa&&avatar.update(a.aa,a)},jb:function(a){a.i!=b.v&&void 0!=a.i&&(b.o().C("",{s:b.v,Ta:"hide",sa:!0}),b.v=a.i);if(void 0==b.va||!1==b.va)a.b=b.e.ub(a.b);avatar=h.o().ya(b.v);avatar.wb(a);b.o().C(a.b,{s:b.v,sa:!0})},Rb:function(){b.A().show()},
ib:function(){if(!b.L||void 0==b.Y)return!1;px={Type:"INIT"};b.Y(px)},Wb:function(a){if(!b.L||void 0==b.Y||void 0==a.ca)return!1;px={Type:"PLAY"};px.Id=a.F;px.Sound=a.ca;px.Param=a;b.Y(px)},getVariable:function(a){return b.g.T(a)},setVariable:function(a,c){b.g.pa({h:a,G:c})},evaluate:function(a){if(void 0==b.ia||void 0==a||3>=a.length)return null;try{return r=b.ia.evaluate(a)}catch(c){return null}}};return b}(""),ypi={};ypi.df=h;
